name: flutter_application_2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  collection: ^1.15.0
  #firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  #firebase_auth: "^0.20.1"
  #firebase_crashlytics: "^0.4.0"
  #cloud_firestore: "^0.16.0"
  #cloud_functions: "^0.9.0"
  #firebase_storage: "^7.0.0"
  #firebase_messaging: "^8.0.0-dev.15"
  #firebase_remote_config: "^0.8.0-dev.0"
  # Updated to work with new core only plugins (no new changes):
  #firebase_admob: "^"
  #firebase_analytics: "^7.0.1"
  #firebase_database: "^6.0.0"
  #firebase_dynamic_links: "^0.7.0"
  #firebase_in_app_messaging: "^0.4.0+1"
  #firebase_performance: "^0.6.0+1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true